// tests/fetch-mbta-data.test.js
// Tests for AC1.1, AC1.2, AC1.4, AC1.5, AC1.6, AC1.7
// Integration tests verify output file structure and content validation

import assert from 'assert';
import { execSync } from 'child_process';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

import { haversineDistance } from '../src/vehicle-math.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '..');
const DATA_FILE = join(PROJECT_ROOT, 'data', 'mbta-static.json');
const SCRIPT_PATH = join(PROJECT_ROOT, 'scripts', 'fetch-mbta-data.mjs');

// ─────────────────────────────────────────────────────────────────────────
// AC1.6: Exit non-zero if MBTA_API_KEY is missing
// ─────────────────────────────────────────────────────────────────────────

function testMissingAPIKey() {
    let exitCode = null;
    let stderr = '';

    try {
        // Run script WITHOUT the API key in environment
        execSync(`node "${SCRIPT_PATH}"`, {
            cwd: PROJECT_ROOT,
            env: { ...process.env, MBTA_API_KEY: undefined },
            stdio: ['pipe', 'pipe', 'pipe'],
        });
    } catch (e) {
        exitCode = e.status;
        stderr = e.stderr ? e.stderr.toString() : '';
    }

    assert.strictEqual(exitCode, 1, `Expected exit code 1, got ${exitCode}`);
    assert(stderr.includes('MBTA_API_KEY environment variable is required'),
        `Expected error message about missing MBTA_API_KEY, got: ${stderr}`);
    console.log('✓ AC1.6: Script exits non-zero when MBTA_API_KEY is missing');
}

// ─────────────────────────────────────────────────────────────────────────
// AC1.1: Script writes data/mbta-static.json and is valid JSON
// AC1.2: Output contains all route types (0-4), all stops, route-stop associations
// AC1.4: Route-stop associations exclude stops >150m from polyline
// AC1.5: Output includes generatedAt Unix timestamp
// ─────────────────────────────────────────────────────────────────────────

function testOutputStructureAndContent() {
    // Load the existing data/mbta-static.json file (generated by fetch-mbta-data.mjs in Phase 2)
    let data;
    try {
        const rawData = readFileSync(DATA_FILE, 'utf-8');
        data = JSON.parse(rawData);
    } catch (e) {
        throw new Error(`Failed to read or parse ${DATA_FILE}: ${e.message}`);
    }

    // AC1.1: File exists and is valid JSON
    assert(data !== null && typeof data === 'object', 'Output must be a valid JSON object');
    console.log('✓ AC1.1: data/mbta-static.json exists and is valid JSON');

    // AC1.5: generatedAt is a Unix timestamp number
    assert(typeof data.generatedAt === 'number', 'generatedAt must be a number');
    const now = Math.floor(Date.now() / 1000);
    // Allow 1 hour tolerance (3600s) for stale files
    assert(data.generatedAt <= now && data.generatedAt > now - 3600,
        `generatedAt (${data.generatedAt}) should be within 1 hour of now (${now})`);
    console.log('✓ AC1.5: Output includes generatedAt Unix timestamp in valid range');

    // AC1.2a: routes array exists and contains types 0-4
    assert(Array.isArray(data.routes), 'routes must be an array');
    assert(data.routes.length > 0, 'routes array must not be empty');

    const routeTypes = new Set(data.routes.map(r => r.type));
    const expectedTypes = [0, 1, 2, 3, 4];
    for (const type of expectedTypes) {
        assert(routeTypes.has(type), `Route type ${type} not found in output`);
    }
    console.log(`✓ AC1.2a: All route types (0-4) present; ${data.routes.length} routes total`);

    // AC1.2b: stops object exists and is non-empty
    assert(typeof data.stops === 'object' && !Array.isArray(data.stops), 'stops must be an object');
    const stopIds = Object.keys(data.stops);
    assert(stopIds.length > 0, 'stops object must have entries');
    console.log(`✓ AC1.2b: Stops object has ${stopIds.length} entries`);

    // AC1.2c: routeStops object has entries for each route
    assert(typeof data.routeStops === 'object' && !Array.isArray(data.routeStops),
        'routeStops must be an object');
    assert(Object.keys(data.routeStops).length > 0, 'routeStops must have entries');
    for (const route of data.routes) {
        assert(route.id in data.routeStops, `Route ${route.id} missing from routeStops`);
    }
    console.log(`✓ AC1.2c: routeStops has entries for all ${data.routes.length} routes`);

    // AC1.4: Each associated stop is within 150m of polyline
    const PROXIMITY_THRESHOLD = 150; // meters
    let violationCount = 0;

    for (const route of data.routes) {
        const polylineCoords = route.polyline.map(([lat, lng]) => ({ lat, lng }));
        const routeStopIds = data.routeStops[route.id] || [];

        for (const stopId of routeStopIds) {
            const stop = data.stops[stopId];
            if (!stop) {
                console.warn(`Warning: Stop ${stopId} referenced in routeStops but not in stops object`);
                continue;
            }

            // Routes with no polyline include all stops unconditionally
            if (polylineCoords.length === 0) {
                continue;
            }

            // Find nearest vertex distance
            let minDist = Infinity;
            for (const vertex of polylineCoords) {
                const d = haversineDistance(
                    stop.lat, stop.lng,
                    vertex.lat, vertex.lng
                );
                minDist = Math.min(minDist, d);
            }

            if (minDist > PROXIMITY_THRESHOLD) {
                violationCount++;
                if (violationCount <= 5) {
                    console.warn(
                        `Warning: Stop ${stop.name} (${stopId}) is ${minDist.toFixed(1)}m from ` +
                        `route ${route.id} polyline (threshold: ${PROXIMITY_THRESHOLD}m)`
                    );
                }
            }
        }
    }

    assert.strictEqual(violationCount, 0,
        `Found ${violationCount} stops exceeding 150m proximity threshold`);
    console.log('✓ AC1.4: All route-stop associations are within 150m of polyline');
}

// ─────────────────────────────────────────────────────────────────────────
// AC1.7: Exit non-zero if MBTA API call fails
// (Tested by running with an invalid API key, which causes real API 403 error)
// ─────────────────────────────────────────────────────────────────────────

function testInvalidAPIKey() {
    let exitCode = null;
    let stderr = '';

    try {
        // Run script WITH an invalid API key (causes 403 from real MBTA API)
        execSync(`node "${SCRIPT_PATH}"`, {
            cwd: PROJECT_ROOT,
            env: { ...process.env, MBTA_API_KEY: 'invalid-test-key-xxx' },
            stdio: ['pipe', 'pipe', 'pipe'],
            timeout: 10000, // 10s timeout
        });
    } catch (e) {
        exitCode = e.status;
        stderr = e.stderr ? e.stderr.toString() : '';
    }

    assert.strictEqual(exitCode, 1,
        `Expected exit code 1 for API failure, got ${exitCode}. stderr: ${stderr}`);
    assert(stderr.includes('error') || stderr.includes('Error'),
        `Expected error message in stderr, got: ${stderr}`);
    console.log('✓ AC1.7: Script exits non-zero when MBTA API call fails');
}

// ─────────────────────────────────────────────────────────────────────────
// Test runner
// ─────────────────────────────────────────────────────────────────────────

function runTests() {
    console.log('=== fetch-mbta-data tests ===\n');

    // AC1.6: Must run without network (no API key)
    testMissingAPIKey();
    console.log('');

    // AC1.1, AC1.2, AC1.4, AC1.5: Validate existing output file
    testOutputStructureAndContent();
    console.log('');

    // AC1.7: API failure handling (uses real API with bad key)
    console.log('Testing API failure handling (making real request with invalid key)...');
    testInvalidAPIKey();

    console.log('\n✓ All fetch-mbta-data tests passed!');
}

try {
    runTests();
} catch (e) {
    console.error('✗ Test failed:', e.message);
    process.exit(1);
}
